-- CHLORO starter catalogue seed.
-- Safe for free-tier testing: inserts only product rows and reuses existing public image paths.
-- Run after the products table exists. Re-running skips products with the same name.

INSERT INTO public.products (
  name,
  description,
  price,
  stock,
  images,
  info,
  water_frequency,
  optimal_place,
  provenance,
  curator_quote,
  season,
  is_featured,
  category,
  tags,
  is_active
)
SELECT
  seed.name,
  seed.description,
  seed.price,
  seed.stock,
  seed.images,
  seed.info,
  seed.water_frequency,
  seed.optimal_place,
  seed.provenance,
  seed.curator_quote,
  seed.season,
  seed.is_featured,
  seed.category,
  seed.tags,
  seed.is_active
FROM (
  VALUES
    (
      'Himalayan Orchid',
      'Elegant orchid for bright indoor corners and gentle watering routines.',
      3200.00::numeric,
      12,
      ARRAY['/orchid.jpg']::text[],
      'A refined flowering plant for customers who want a premium botanical centerpiece.',
      'Every 7 days after checking the bark mix',
      'Bright indirect window, away from harsh noon sun',
      'Selected from Nepal-friendly greenhouse stock',
      'A quiet bloom with couture-level presence.',
      'Spring',
      true,
      'Indoor Plants',
      ARRAY['flowering', 'orchid', 'premium', 'ai-diagnosis']::text[],
      true
    ),
    (
      'Monstera Deliciosa',
      'Large split-leaf foliage plant for statement rooms.',
      4500.00::numeric,
      8,
      ARRAY['/ful.jpg']::text[],
      'Best for customers who want a dramatic tropical leaf with easy visual impact.',
      'Every 6 to 8 days',
      'Bright filtered light with room to spread',
      'Tropical foliage selected for indoor Nepal homes',
      'Architectural leaves that make a room feel collected.',
      'All Year',
      true,
      'Indoor Plants',
      ARRAY['statement', 'foliage', 'monstera', 'low-maintenance']::text[],
      true
    ),
    (
      'Snake Plant Laurentii',
      'Hardy upright plant for bedrooms, desks, and low-light corners.',
      1800.00::numeric,
      20,
      ARRAY['/money.jpg']::text[],
      'A forgiving plant for new plant parents and busy students.',
      'Every 12 to 18 days',
      'Low to bright indirect light',
      'Nursery-grown for indoor resilience',
      'Sharp lines, soft maintenance.',
      'All Year',
      false,
      'Indoor Plants',
      ARRAY['beginner', 'low-light', 'air-purifying']::text[],
      true
    ),
    (
      'Anthurium Rouge',
      'Glossy leaves with red spathes for a fashion-forward floral accent.',
      2600.00::numeric,
      10,
      ARRAY['/lily.jpg']::text[],
      'Works well as a gift plant because the flowers hold shape for weeks.',
      'Every 5 to 7 days',
      'Bright indirect light with moderate humidity',
      'Greenhouse-grown flowering tropical',
      'A lacquered red note against calm interiors.',
      'Summer',
      false,
      'Indoor Plants',
      ARRAY['flowering', 'giftable', 'humidity']::text[],
      true
    ),
    (
      'Ficus Lyrata',
      'Sculptural fiddle leaf fig for larger living spaces.',
      5200.00::numeric,
      6,
      ARRAY['/lof.jpg']::text[],
      'A premium floor plant that needs stable light and patient watering.',
      'Every 7 to 10 days',
      'Bright stable light, away from cold drafts',
      'Selected for broad leaf structure',
      'A large statement plant for elegant homes.',
      'All Year',
      true,
      'Indoor Plants',
      ARRAY['statement', 'floor-plant', 'bright-light']::text[],
      true
    ),
    (
      'Peace Lily Petite',
      'Compact white blooming plant for soft corners and work tables.',
      1500.00::numeric,
      18,
      ARRAY['/lily.jpg']::text[],
      'A classic indoor plant that signals thirst with drooping leaves.',
      'Every 5 to 7 days',
      'Medium indirect light',
      'Local nursery selection',
      'Quiet, white, and graceful.',
      'All Year',
      false,
      'Indoor Plants',
      ARRAY['flowering', 'beginner', 'low-light']::text[],
      true
    ),
    (
      'Brass Watering Can',
      'Slim long-spout watering can for controlled indoor watering.',
      1400.00::numeric,
      15,
      ARRAY['/cat.jpg']::text[],
      'Useful after AI diagnosis when care advice requires careful soil watering.',
      'Tool',
      'Use for indoor pots and balcony planters',
      'Care tool collection',
      'Precision watering, but make it atelier.',
      'All Year',
      false,
      'Care Tools',
      ARRAY['care', 'tool', 'watering', 'ai-diagnosis', 'plant-care']::text[],
      true
    ),
    (
      'Soil Moisture Meter',
      'Simple probe to check whether soil is dry before watering.',
      950.00::numeric,
      22,
      ARRAY['/cat.jpg']::text[],
      'Connects directly to AI care advice by reducing overwatering mistakes.',
      'Tool',
      'Use before watering indoor plants',
      'Care tool collection',
      'The cheapest way to stop guessing.',
      'All Year',
      true,
      'Care Tools',
      ARRAY['care', 'tool', 'meter', 'watering', 'diagnosis', 'ai-diagnosis']::text[],
      true
    ),
    (
      'Neem Leaf Care Spray',
      'Gentle neem-based leaf care spray for first-response pest routines.',
      780.00::numeric,
      28,
      ARRAY['/ful.jpg']::text[],
      'Recommended only for mild pest-support care, with cautious AI diagnosis guidance.',
      'Tool',
      'Apply in shade and test a small leaf first',
      'Care tool collection',
      'A practical first step before panic.',
      'Monsoon',
      true,
      'Care Tools',
      ARRAY['care', 'neem', 'spray', 'pest-care', 'ai-diagnosis']::text[],
      true
    ),
    (
      'Orchid Bark Mix',
      'Chunky bark mix for orchid roots and airy drainage.',
      650.00::numeric,
      16,
      ARRAY['/orchid.jpg']::text[],
      'Useful for orchid recovery advice, especially when roots need more air.',
      'Tool',
      'Use while repotting orchids',
      'Care mix collection',
      'Breathable structure for fussy roots.',
      'All Year',
      false,
      'Care Tools',
      ARRAY['care', 'soil', 'orchid', 'root-care', 'ai-diagnosis']::text[],
      true
    ),
    (
      'Sterile Pruning Scissors',
      'Compact scissors for removing damaged leaves and soft stems.',
      1200.00::numeric,
      11,
      ARRAY['/cat.jpg']::text[],
      'Supports AI diagnosis steps such as trimming infected or damaged tissue.',
      'Tool',
      'Clean before and after every cut',
      'Care tool collection',
      'Clean cuts are a care language.',
      'All Year',
      false,
      'Care Tools',
      ARRAY['care', 'tool', 'pruning', 'fungal-care', 'ai-diagnosis']::text[],
      true
    ),
    (
      'Foliar Recovery Mist',
      'Light plant mist for dusty leaves and humidity support.',
      900.00::numeric,
      19,
      ARRAY['/ful.jpg']::text[],
      'For gentle foliage cleaning and humidity support when appropriate.',
      'Tool',
      'Mist lightly in the morning only',
      'Plant care products collection',
      'A small ritual for leaf shine.',
      'Winter',
      false,
      'Care Tools',
      ARRAY['care', 'mist', 'foliar', 'humidity', 'ai-diagnosis']::text[],
      true
    ),
    (
      'Lavender Gift Crate',
      'Gift-ready lavender bundle with simple care card.',
      2400.00::numeric,
      9,
      ARRAY['/lavender.jpg']::text[],
      'A safe elegant gift for birthdays, thank-yous, and housewarmings.',
      'Every 7 to 10 days',
      'Sunny window or bright balcony',
      'Gift collection',
      'Fragrant, calm, and beautifully wrapped.',
      'Spring',
      true,
      'Gifts',
      ARRAY['gift', 'lavender', 'fragrant', 'bundle']::text[],
      true
    ),
    (
      'Terrarium Glass Garden',
      'Mini glass terrarium with moss-inspired styling.',
      3100.00::numeric,
      7,
      ARRAY['/phool.png']::text[],
      'A premium compact gift for desks and shelves.',
      'Mist lightly every 10 to 14 days',
      'Bright indirect light',
      'Gift collection',
      'A tiny enclosed world for elegant desks.',
      'All Year',
      false,
      'Gifts',
      ARRAY['gift', 'terrarium', 'desk', 'premium']::text[],
      true
    ),
    (
      'Ceramic Vessel Duo',
      'Two neutral ceramic vessels for small plants or fresh cuts.',
      1700.00::numeric,
      14,
      ARRAY['/cat.jpg']::text[],
      'Pairs with plants, gifts, and seasonal arrangements.',
      'Accessory',
      'Indoor shelves, coffee tables, and bedside corners',
      'Gift collection',
      'Minimal vessels, maximum polish.',
      'All Year',
      false,
      'Gifts',
      ARRAY['gift', 'ceramic', 'vessel', 'home']::text[],
      true
    )
) AS seed (
  name,
  description,
  price,
  stock,
  images,
  info,
  water_frequency,
  optimal_place,
  provenance,
  curator_quote,
  season,
  is_featured,
  category,
  tags,
  is_active
)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.products existing
  WHERE lower(existing.name) = lower(seed.name)
);

NOTIFY pgrst, 'reload schema';
